name: new_gardenifi_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  duration_picker: ^1.1.1
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.28.10
  
  flutter_localizations:
    sdk: flutter
  
  flutter_riverpod: ^2.4.5
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: ^0.18.1
  mqtt_client: ^10.0.0
  package_info_plus: ^5.0.1
  rename_app: ^1.3.1
  shared_preferences: ^2.2.2
  typed_data: ^1.3.2
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1

# TODO: delete it
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#cefad0"
  image: assets/images/splash_light.png
  color_dark: "#18392b"
  image_dark: assets/images/splash_dark.png

  android_12:
    color: "#cefad0"
    image: assets/images/splash_light.png
    color_dark: "#18392b"
    image_dark: assets/images/splash_dark.png

  web: false
  


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
