name: Build
on:
  push:
    branches:
      - main
    paths:
      - '!pubspec.yaml' # Exclude pubspec.yaml
  workflow_dispatch:
  workflow_call:

jobs:
  common-job:
    runs-on: ubuntu-latest
    name: Build, Check Code Conventions, Formatting, Linting, run Unit Tests and check UT code coverage on ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install

      - name: Run pre-commit and flutter tests
        run: |
          flutter pub get
          pre-commit run --all-files --config .pre-commit-config-actions.yaml

      # - name: Run flutter analyzer
      #   run: |
      #     flutter analyze

      - name: Run flutter tests with coverage
        run: |
          flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
