name: Precommit
on: [push, workflow_dispatch, workflow_call]
jobs:
  common-job:
    runs-on: ubuntu-latest
    name: Build, Check Code Conventions, Formatting, Linting, run Unit Tests and check UT code coverage on ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install

      - name: Run pre-commit and flutter tests
        run: |
          pre-commit run --all-files

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          slug: gardenifi/raspirri_app
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
