name: Release

on:
  push:
    tags:
      - '*' # Listen for all tag pushes

jobs:
  pre-commit:
    uses: gardenifi/raspirri_app/.github/workflows/precommit.yml@main

  release:
    needs: pre-commit
    runs-on: ubuntu-latest
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies
        run: |
          git config --global user.email "tom.makrodi@gmail.com"
          git config --global user.name "Tom Makrodimos"
          npm install -g auto-changelog
          python -m pip install --upgrade pip
          pip install wheel==0.42.0
          pip install invoke==2.2.0

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Generate Changelog
        run: |
          auto-changelog --template keepachangelog
          # Check if there are changes to the changelog
          if git diff --exit-code CHANGELOG.md; then
            echo "No changes to CHANGELOG.md"
            exit 0
          fi
          # Add, commit, and push the changes
          git add CHANGELOG.md
          git commit -m "Auto-generated changelog"
          git push

      - name: Upload new release to assets
        run: |
          NEW_VERSION=$(git describe --abbrev=0 --tags | cut -d'v' -f2) INSTALLATION_PATH=./tmp invoke upload-to-github
